### ISSUE TITLE
hello i need some advice

### ISSUE THREAD

**Issue by NanoFog** [Suraf/HideLoginScreenUI#1]
![2023-08-16_210151](https://github.com/Suraf/HideLoginScreenUI/assets/36675790/e2c86d6f-71c3-4774-86d3-bd2394fee7c1)
![2023-08-16_210217](https://github.com/Suraf/HideLoginScreenUI/assets/36675790/55b1a2c9-4c48-42a1-b8d7-f3d1d1f4b918)

^_^ hello! I used your mod [HideLoginScreenUI] Please tell me how to hide fonts. i have tried a lot of things. I want to take a video of the login screen. your mod hide the buttons but not the fonts and the logo in the upper left corner. what are the solutions??? thanks in advance!!!

**Comment by Suraf** [comment]
I can add the files to hide the logos but still at a standby with the font, since Shadowlands (and BCC), it does [this](https://github.com/Suraf/HideLoginScreenUI/blob/master/Issue.jpg).

**Comment by NanoFog** [comment]
> I can add the files to hide the logos but still at a standby with the font, since Shadowlands (and BCC), it does [this](https://github.com/Suraf/HideLoginScreenUI/blob/master/Issue.jpg).

I understand! I will look forward to a solution to this problem. Thank you.

**Comment by Maia-Everett** [comment]
> I can add the files to hide the logos but still at a standby with the font, since Shadowlands (and BCC), it does [this](https://github.com/Suraf/HideLoginScreenUI/blob/master/Issue.jpg).

My psychic powers tell me that the Russian version of WoW, seen on the OP's screenshot, uses a separate font for the UI, which includes Cyrillic glyphs. We probably need to find what its filename is, and replace it too.

**Comment by NanoFog** [comment]
Hello Maia Everett! thanks for the idea! very interesting thought. I'll definitely try it very soon. ^__^ 👍❤

**Comment by Maia-Everett** [comment]
I've opened a pull request to fix the issue with fonts. Feel free to use my branch in the interim.

https://github.com/Suraf/HideLoginScreenUI/pull/2
